# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4sJnC6uYX5lNx3jDl9LDK4WlKDeamS3
"""

name = input("Enter your name: ")
print("Welcome,", name)

score = 0

while True:
    answer = input("Is Python a programming language? (yes/no): ").lower()
    if answer == "yes" or answer == "no":
        if answer == "yes":
            score += 1
        break
    print("Please enter only yes or no.")

while True:
    answer = input("Can Python be used to create web applications? (yes/no): ").lower()
    if answer == "yes" or answer == "no":
        if answer == "yes":
            score += 1
        break
    print("Please enter only yes or no.")

while True:
    answer = input("Does Python require semicolons at the end of every statement? (yes/no): ").lower()
    if answer == "yes" or answer == "no":
        if answer == "no":
            score += 1
        break
    print("Please enter only yes or no.")


print("Your final score is", score, "/3")

if score == 3:
    print("Outstanding! You got everything correct! ")
elif score == 2:
    print("Great job! You did very well. ")
elif score == 1:
    print("Good effort! Keep practicing to improve. ")
else:
    print("Don't give up! Practice more and you'll do better next time. ")

